In [1]:
import pandas as pd
import pyodbc 
import pickle
import zlib
import redis

conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=DESKTOP-BQB5EK3\DEVELOPER2022;'
                      'Database=BikeStores;'
                      'Trusted_Connection=yes;')

df = pd.read_sql_query("SELECT * FROM [BikeStores].[sales].[staffs]", conn)

df.head()

C:\Users\pmartinez\AppData\Local\Temp\ipykernel_14232\3976992124.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM [BikeStores].[sales].[staffs]", conn)

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [3]:
r = redis.Redis(host='localhost', port=6379, db=0)

context = zlib.compress( pickle.dumps(df))
r.set("Empleados", context)

True

In [4]:
r.get("Empleados")

b'x\x9c\xbdUKo\xdbF\x10\x96d\xd1\x92\xed"A\xd06v\n\xb7\x08z\xb2\x0f&\xe28\x8a\x13\xa0\x80\x05\xdb\xc8\xc3\xac\xd5"-\xda\\\x02bI\xad\xc8\x8d\x96K\x82\\\xcaU\x91 \xed\xa1I\x1c\xec\xcd\xdbc\xffa\x0f=\xf6\xd6\xce,IW\x94\xedk)\x88\xb3\x9c\xd7\xce7;\xb3\xf3K\xfb\xf7?:\r\xf3\xa8\x1b\t\x11C\x92\xd9~\x9cR{\x94\x92\x88j\xb5tH$yd\xd6gz\xf3W\xfdZo\xa8\xb6\x1b\x05\xa9V_\xcc\xaa3!i*\x08\xcf\xec\x88\x08\x12\xd04\xd3\xea\xa3}\x1e\xfb\xe3\xe3\xe2\x1b\xcc\xd5\xcd\xd2\xc2\xe5\xcc\xcb\xfe3\xd1\xea\xba\x9b\x8b\x84\xf9cN]\x0fmP\xf9S\x91G\xc9\xb4\xf0\x1e\xe5\\2\x92\xa6d\n^\xdd\x94\xfa\xb1\xc8d\x9a\xfb\x12\x15-\xa3\xa8U\x07|\x1b\x953\xed4~\xd3\x07MO\xbf\xd3\xcf\xf4\x86\xd3\x84\xdf\xca[\x1d^W\xd6PN\x13D\xa2Z\xa3\x07\xfa\xf4}!_P\xcd\xaf\xf4`08\xfa\x07\x1e\xf3r\x1aR{\xa7\x07\xcf\x8b\xc4\xfc\xfd\xa6\xa0\x7f\xed\x15\xb4\xd1\xaf\xd3\x8a\xffI\xbfN+\xfez\x7f\x9ejp\xaf\xba^\xce\x00\x96\x00\xfcV\xc6\x99\x8fq9\x1d\xa7\xeb41,\xa7\x85\xefp%\xbc\x16\xde@8\xe1\xc7\x15\x98\x05\x03fM\xb5\xd8\x0c\x84p\xfd\x12\x00\xfb\xddf\xa3\xd1,\x83m\x95t\xa1\xa4\xed\x92Z%],iY\r\x8dnI\x97J\xba\\\xd2?K\x07\x95\xdf\xff\x9b\xb6\xae\xa0\x0bW\xd0\xca\x0es~I2\xe1c\xeb\xf4`\xadT\xba\x90\r\xb4\xba\xfa(\xda\xd5Q|S\xab\xa6Ws\xd5\xb4\x87\x87\xf1\x02:\xa7\xf3\x88x,\xe6D\xab\xc5c\x96\xd2),\xac\xc7T\x08d\xfc\xc0\xd2\x80A\xc7u\x8f\x88\x10TJl\xbec\x92\xfa\x94SAQN\x05\x93\xa0\xd8v\x08g`\xf75\x99\xa2\xa3\xe5}l\xa2t\xc8\x8c\xd2\xb7\xd0x,\x86^8"\xfe8\x8b\x05\xb8;\x88\x13\xca\xa1\xef\x80\xf9\x1d\x85\xfe\x10(\xfe\x91\x05AQy\x87d\xc2@f\xed\xc7ShR\xb5xH\x04\xa3\x1c\xf7#i@@\xa3\xf3=XQ\x0e\xac\xce\x938\xcf\xa4q\n\x81A\xe5\xd2\x9f\xb5\xfalT@\xb2_\x16;\xf6=6\xa6\x99\x9d\x85q\x02\xc2\xc8\xa0\x84&.b\xa8\t\xd7\x02DngEP5\xd1\xad\x89I\x86}R\x84Y\x97\xbd,\xf3c\x0f1\xf4\xb9\xfd\xaa\x84\xd9\x1e\xe2\xa9\xef71\x19\x043DX\x13\xdd\x1cCN\xed\x89A\\\xb7\xe1\x98e[\x16)\xa8\x89>\xf7\xce\x13o\x87Ebj\xf2U&\x82\xa8L\xd3\xdd\xed>\xac\x19\x87DDZ]\xdbx\xb0\xb3\xbdy\xbb\xd7\xebm\xc1\xff\xde<\xa37\xcf\xb8?\xcf\xd8EFo\xfb\xfe\xe6\xed\x9d\xdd\x87[\xf7\xe0\x99g\xf4\xe6\x19\xc6\xc7\xc3\xdd\xbb\xe0c\xe7\xce\xf9.\xb3\x8c\x0b\x1a\xbbz@\xb1g\xbe\x84B\xb7f/\xa5w\x1aky\xad~\xfd\x0f\xe9O\x00\xdd#\x19\x94\xe1\xb2+\xe8\x89\xfb\x14yp\xa7\x85\xb9\xb2\xaa\xb5\x19\x1fC\x18)\xfab3u\xe1c\xcf\xb4I7\x93d4r\xb1.\x97G,\xcd\xa4+\x8aa\xc4\xc9\xf9\xda\xa2\x98P\xa0I\x18\x9b\xd2\'\xbed\x13\xec\x1f8\x89\x94\x16\xc6\xe5,\xc2\x0f\x84\xa2\xda\xc6v\x90\xbf\xc5~>Q\xb7.\x83\x00\xc5\x18 \x86gHg\xe2\x0e?\x0c\xe0\x9e\x96p\xa20^T\x1bvI\xb4\xb3\x82\x0b\n\x8b\xa6\xf1I\xf1\x05\xf3\x11\xa6\x0cD\x8b8\xab1\xeaFT\x12\x03\xfc\x05\xc4L\xa4\x84\x01\xf9\x1a\xa2vG\x9c\x04f\xb9J8\x8fO2w\x98\'0\x0c\x88\xa4.\'\x1e\x85\xe9\xf8>\xcb=\xfb_cz_X'

In [5]:
datos_analisis = pickle.loads(zlib.decompress(r.get("Empleados")))
datos_analisis

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0
5,6,Marcelene,Boyer,marcelene.boyer@bikes.shop,(516) 379-4445,1,2,5.0
6,7,Venita,Daniel,venita.daniel@bikes.shop,(516) 379-4446,1,2,5.0
7,8,Kali,Vargas,kali.vargas@bikes.shop,(972) 530-5555,1,3,1.0
8,9,Layla,Terrell,layla.terrell@bikes.shop,(972) 530-5556,1,3,7.0
9,10,Bernardine,Houston,bernardine.houston@bikes.shop,(972) 530-5557,1,3,7.0
10,1004,Persio,Martinez,ingmartinez21@gmail.com,None,1,1,7.0

In [6]:
r.get("Empleados")

b'x\x9c\xbdUKo\xdbF\x10\x96d\xd1\x92\xed"A\xd06v\n\xb7\x08z\xb2\x0f&\xe28\x8a\x13\xa0\x80\x05\xdb\xc8\xc3\xac\xd5"-\xda\\\x02bI\xad\xc8\x8d\x96K\x82\\\xcaU\x91 \xed\xa1I\x1c\xec\xcd\xdbc\xffa\x0f=\xf6\xd6\xce,IW\x94\xedk)\x88\xb3\x9c\xd7\xce7;\xb3\xf3K\xfb\xf7?:\r\xf3\xa8\x1b\t\x11C\x92\xd9~\x9cR{\x94\x92\x88j\xb5tH$yd\xd6gz\xf3W\xfdZo\xa8\xb6\x1b\x05\xa9V_\xcc\xaa3!i*\x08\xcf\xec\x88\x08\x12\xd04\xd3\xea\xa3}\x1e\xfb\xe3\xe3\xe2\x1b\xcc\xd5\xcd\xd2\xc2\xe5\xcc\xcb\xfe3\xd1\xea\xba\x9b\x8b\x84\xf9cN]\x0fmP\xf9S\x91G\xc9\xb4\xf0\x1e\xe5\\2\x92\xa6d\n^\xdd\x94\xfa\xb1\xc8d\x9a\xfb\x12\x15-\xa3\xa8U\x07|\x1b\x953\xed4~\xd3\x07MO\xbf\xd3\xcf\xf4\x86\xd3\x84\xdf\xca[\x1d^W\xd6PN\x13D\xa2Z\xa3\x07\xfa\xf4}!_P\xcd\xaf\xf4`08\xfa\x07\x1e\xf3r\x1aR{\xa7\x07\xcf\x8b\xc4\xfc\xfd\xa6\xa0\x7f\xed\x15\xb4\xd1\xaf\xd3\x8a\xffI\xbfN+\xfez\x7f\x9ejp\xaf\xba^\xce\x00\x96\x00\xfcV\xc6\x99\x8fq9\x1d\xa7\xeb41,\xa7\x85\xefp%\xbc\x16\xde@8\xe1\xc7\x15\x98\x05\x03fM\xb5\xd8\x0c\x84p\xfd\x12\x00\xfb\xddf\xa3\xd1,\x83m\x95t\xa1\xa4\xed\x92Z%],iY\r\x8dnI\x97J\xba\\\xd2?K\x07\x95\xdf\xff\x9b\xb6\xae\xa0\x0bW\xd0\xca\x0es~I2\xe1c\xeb\xf4`\xadT\xba\x90\r\xb4\xba\xfa(\xda\xd5Q|S\xab\xa6Ws\xd5\xb4\x87\x87\xf1\x02:\xa7\xf3\x88x,\xe6D\xab\xc5c\x96\xd2),\xac\xc7T\x08d\xfc\xc0\xd2\x80A\xc7u\x8f\x88\x10TJl\xbec\x92\xfa\x94SAQN\x05\x93\xa0\xd8v\x08g`\xf75\x99\xa2\xa3\xe5}l\xa2t\xc8\x8c\xd2\xb7\xd0x,\x86^8"\xfe8\x8b\x05\xb8;\x88\x13\xca\xa1\xef\x80\xf9\x1d\x85\xfe\x10(\xfe\x91\x05AQy\x87d\xc2@f\xed\xc7ShR\xb5xH\x04\xa3\x1c\xf7#i@@\xa3\xf3=XQ\x0e\xac\xce\x938\xcf\xa4q\n\x81A\xe5\xd2\x9f\xb5\xfalT@\xb2_\x16;\xf6=6\xa6\x99\x9d\x85q\x02\xc2\xc8\xa0\x84&.b\xa8\t\xd7\x02DngEP5\xd1\xad\x89I\x86}R\x84Y\x97\xbd,\xf3c\x0f1\xf4\xb9\xfd\xaa\x84\xd9\x1e\xe2\xa9\xef71\x19\x043DX\x13\xdd\x1cCN\xed\x89A\\\xb7\xe1\x98e[\x16)\xa8\x89>\xf7\xce\x13o\x87Ebj\xf2U&\x82\xa8L\xd3\xdd\xed>\xac\x19\x87DDZ]\xdbx\xb0\xb3\xbdy\xbb\xd7\xebm\xc1\xff\xde<\xa37\xcf\xb8?\xcf\xd8EFo\xfb\xfe\xe6\xed\x9d\xdd\x87[\xf7\xe0\x99g\xf4\xe6\x19\xc6\xc7\xc3\xdd\xbb\xe0c\xe7\xce\xf9.\xb3\x8c\x0b\x1a\xbbz@\xb1g\xbe\x84B\xb7f/\xa5w\x1aky\xad~\xfd\x0f\xe9O\x00\xdd#\x19\x94\xe1\xb2+\xe8\x89\xfb\x14yp\xa7\x85\xb9\xb2\xaa\xb5\x19\x1fC\x18)\xfab3u\xe1c\xcf\xb4I7\x93d4r\xb1.\x97G,\xcd\xa4+\x8aa\xc4\xc9\xf9\xda\xa2\x98P\xa0I\x18\x9b\xd2\'\xbed\x13\xec\x1f8\x89\x94\x16\xc6\xe5,\xc2\x0f\x84\xa2\xda\xc6v\x90\xbf\xc5~>Q\xb7.\x83\x00\xc5\x18 \x86gHg\xe2\x0e?\x0c\xe0\x9e\x96p\xa20^T\x1bvI\xb4\xb3\x82\x0b\n\x8b\xa6\xf1I\xf1\x05\xf3\x11\xa6\x0cD\x8b8\xab1\xeaFT\x12\x03\xfc\x05\xc4L\xa4\x84\x01\xf9\x1a\xa2vG\x9c\x04f\xb9J8\x8fO2w\x98\'0\x0c\x88\xa4.\'\x1e\x85\xe9\xf8>\xcb=\xfb_cz_X'

In [7]:
tiempo = 20
r.setex("Empleados",tiempo, context)

True

In [8]:
r.get("Empleados")

b'x\x9c\xbdUKo\xdbF\x10\x96d\xd1\x92\xed"A\xd06v\n\xb7\x08z\xb2\x0f&\xe28\x8a\x13\xa0\x80\x05\xdb\xc8\xc3\xac\xd5"-\xda\\\x02bI\xad\xc8\x8d\x96K\x82\\\xcaU\x91 \xed\xa1I\x1c\xec\xcd\xdbc\xffa\x0f=\xf6\xd6\xce,IW\x94\xedk)\x88\xb3\x9c\xd7\xce7;\xb3\xf3K\xfb\xf7?:\r\xf3\xa8\x1b\t\x11C\x92\xd9~\x9cR{\x94\x92\x88j\xb5tH$yd\xd6gz\xf3W\xfdZo\xa8\xb6\x1b\x05\xa9V_\xcc\xaa3!i*\x08\xcf\xec\x88\x08\x12\xd04\xd3\xea\xa3}\x1e\xfb\xe3\xe3\xe2\x1b\xcc\xd5\xcd\xd2\xc2\xe5\xcc\xcb\xfe3\xd1\xea\xba\x9b\x8b\x84\xf9cN]\x0fmP\xf9S\x91G\xc9\xb4\xf0\x1e\xe5\\2\x92\xa6d\n^\xdd\x94\xfa\xb1\xc8d\x9a\xfb\x12\x15-\xa3\xa8U\x07|\x1b\x953\xed4~\xd3\x07MO\xbf\xd3\xcf\xf4\x86\xd3\x84\xdf\xca[\x1d^W\xd6PN\x13D\xa2Z\xa3\x07\xfa\xf4}!_P\xcd\xaf\xf4`08\xfa\x07\x1e\xf3r\x1aR{\xa7\x07\xcf\x8b\xc4\xfc\xfd\xa6\xa0\x7f\xed\x15\xb4\xd1\xaf\xd3\x8a\xffI\xbfN+\xfez\x7f\x9ejp\xaf\xba^\xce\x00\x96\x00\xfcV\xc6\x99\x8fq9\x1d\xa7\xeb41,\xa7\x85\xefp%\xbc\x16\xde@8\xe1\xc7\x15\x98\x05\x03fM\xb5\xd8\x0c\x84p\xfd\x12\x00\xfb\xddf\xa3\xd1,\x83m\x95t\xa1\xa4\xed\x92Z%],iY\r\x8dnI\x97J\xba\\\xd2?K\x07\x95\xdf\xff\x9b\xb6\xae\xa0\x0bW\xd0\xca\x0es~I2\xe1c\xeb\xf4`\xadT\xba\x90\r\xb4\xba\xfa(\xda\xd5Q|S\xab\xa6Ws\xd5\xb4\x87\x87\xf1\x02:\xa7\xf3\x88x,\xe6D\xab\xc5c\x96\xd2),\xac\xc7T\x08d\xfc\xc0\xd2\x80A\xc7u\x8f\x88\x10TJl\xbec\x92\xfa\x94SAQN\x05\x93\xa0\xd8v\x08g`\xf75\x99\xa2\xa3\xe5}l\xa2t\xc8\x8c\xd2\xb7\xd0x,\x86^8"\xfe8\x8b\x05\xb8;\x88\x13\xca\xa1\xef\x80\xf9\x1d\x85\xfe\x10(\xfe\x91\x05AQy\x87d\xc2@f\xed\xc7ShR\xb5xH\x04\xa3\x1c\xf7#i@@\xa3\xf3=XQ\x0e\xac\xce\x938\xcf\xa4q\n\x81A\xe5\xd2\x9f\xb5\xfalT@\xb2_\x16;\xf6=6\xa6\x99\x9d\x85q\x02\xc2\xc8\xa0\x84&.b\xa8\t\xd7\x02DngEP5\xd1\xad\x89I\x86}R\x84Y\x97\xbd,\xf3c\x0f1\xf4\xb9\xfd\xaa\x84\xd9\x1e\xe2\xa9\xef71\x19\x043DX\x13\xdd\x1cCN\xed\x89A\\\xb7\xe1\x98e[\x16)\xa8\x89>\xf7\xce\x13o\x87Ebj\xf2U&\x82\xa8L\xd3\xdd\xed>\xac\x19\x87DDZ]\xdbx\xb0\xb3\xbdy\xbb\xd7\xebm\xc1\xff\xde<\xa37\xcf\xb8?\xcf\xd8EFo\xfb\xfe\xe6\xed\x9d\xdd\x87[\xf7\xe0\x99g\xf4\xe6\x19\xc6\xc7\xc3\xdd\xbb\xe0c\xe7\xce\xf9.\xb3\x8c\x0b\x1a\xbbz@\xb1g\xbe\x84B\xb7f/\xa5w\x1aky\xad~\xfd\x0f\xe9O\x00\xdd#\x19\x94\xe1\xb2+\xe8\x89\xfb\x14yp\xa7\x85\xb9\xb2\xaa\xb5\x19\x1fC\x18)\xfab3u\xe1c\xcf\xb4I7\x93d4r\xb1.\x97G,\xcd\xa4+\x8aa\xc4\xc9\xf9\xda\xa2\x98P\xa0I\x18\x9b\xd2\'\xbed\x13\xec\x1f8\x89\x94\x16\xc6\xe5,\xc2\x0f\x84\xa2\xda\xc6v\x90\xbf\xc5~>Q\xb7.\x83\x00\xc5\x18 \x86gHg\xe2\x0e?\x0c\xe0\x9e\x96p\xa20^T\x1bvI\xb4\xb3\x82\x0b\n\x8b\xa6\xf1I\xf1\x05\xf3\x11\xa6\x0cD\x8b8\xab1\xeaFT\x12\x03\xfc\x05\xc4L\xa4\x84\x01\xf9\x1a\xa2vG\x9c\x04f\xb9J8\x8fO2w\x98\'0\x0c\x88\xa4.\'\x1e\x85\xe9\xf8>\xcb=\xfb_cz_X'